[package]
name = "vm"
version = "0.1.0"
license = "GPLv3"
authors = ["Leon Heidelbach <leon.heidelbach@hhu.de>"]
description = "The Hack Virtual Machine that interprets Hack VM code."
edition = "2021"
workspace = ".."

[dependencies]
anyhow = "1.0.82"
shared = { path = "../shared" }
